//export 792;
export Company.Validator;
export Kabe.Collections.Arrays;
export Kabe
    .    Stuff;

export Kabe.Yup.Even.Moar;
export Kabe.Even.Yup;

import Kabe.Collections;
import Kabe.Nope;
import Kabe.Even.Blargh;
import Garbage.Nope;

Process();

int32 GlobalGarbage;

int32 Average(int32 a, int32 b)
{
    return (a + b) / 2;
}

(int32 low, int32 high) LowToHigh (int32 a, int32 b)
{
    import System.Memory;
    HeapLoader();
}

LowToHigh (int32 a, int32 b) to (int32 low, int32 high)
{
    return b < a ? b, a : a, b;
    
    low = min(a, b);
    high = max(a, b);
    
    low = 7;
    
    // 500 lines later
    
    high = 12;
}

func Average : (int32 a, int32 b) -> (int32 result)
{
    result = (a + b) / 2;
}

Save : (int32 a, int32 b)
{
    /** This method is
    super crazy. ****/
    WriteToFile(a);
    /* Even /* crazier */ */
    WriteToFile(b);
}

int32 Average(int32[] values)
{
    return sum(values) / values.count;
}

int32 Average(int32* values, int32 count)
{
    return ...;
}

int main(int32 argc, int8** argv)
{
    Write("The \"average\" is ", Average(789, 945215784225), "...\n");
    Write('a', '\n');
    return 0;
    
    Failure("\j");
}

