export Company.Validator;
export 792;
export Kabe.Collections.Arrays;
export Kabe
    .    Stuff;
export Kabe.Yup.Even.Moar;

Process();

int32 Average(int32 a, int32 b)
{
    return (a + b) / 2;
}

int32 Average(int32[] values)
{
    return sum(values) / values.count;
}

int32 Average(int32* values, int32 count)
{
    return ...;
}

int main(int32 argc, int8** argv)
{
    Write("The \"average\" is ", Average(789, 945215784225), "...\n");
    return 0;
}

